version: 0.0
os: linux
files:
  - source: /app
    destination: /home/iot/doorSensor
permissions:
  - object: /
    pattern: "**"
    owner: iot
    group: iot
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 500
      runas: iot
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 500
      runas: iot
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 500
      runas: iot
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 30
      runas: iot
